routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
;

Route::get('/','IndexController@index')->name('index');

Route::namespace('Auth')->prefix('auth')->name('auth.')->group(function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login')->middleware('guest');
    Route::post('/login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

Route::middleware('auth')->namespace('Admin')->prefix('admin')->name('admin.')->group(function () {

    Route::resource('/product', 'ProductController');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    public $timestamps = false;

    protected $fillable = [
        'orderCode', 'name', 'imgName', 'statusId', 'address',
        'cusName','fbName', 'fbLink',
        'createAt', 'updateAt'
    ];

    public function Status() {
        return $this->hasOne('App\Status','id', 'statusId');
    }
}

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Status;
use App\Product;
use Image;
use File;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $codeKeyword = $request->input('code',null);
        $product = Product::with('Status')
            ->orderBy('id', 'desc');
        if($codeKeyword !== null) {
            $product = $product->where('orderCode',$codeKeyword);
        }
            $product = $product->paginate(9);

        return view('product.index', compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $status = Status::all();
        $product = [];
        return view('product.manage',compact(
            'status',
                  'product'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->hasFile('imageName')) {
            $image = $request->file('imageName');
            $filename = time().'.'.$image->extension();

            $destinationPath = public_path('/thumbnail');
            $img = Image::make($image->path());
            $img->resize(100, 100, function ($constraint) {
                $constraint->aspectRatio();
            })->save($destinationPath.'/'.$filename);
        }

        Product::create([
            'orderCode' => $request->orderCode,
            'name' => $request->productName,
            'imgName' => !empty($filename) ? $filename : 'default.png',
            'statusId' => $request->statusId,
            'address' => $request->address,
            'cusName' => $request->cusName,
            'fbName' => $request->fbName,
            'fbLink' => $request->fbLink,
            'createAt' => now(),
            'updateAt' => now()
        ]);

        return redirect()->route('admin.product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $status = Status::all();
        $text = "แก้ไข";
        $product = product::find($id);
        return view('product.manage',compact('product','status','text'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $product = Product::find($id);

        if($request->hasFile('imageName')) {

            if($product->imgName != 'default.png') {
                File::delete(public_path('/thumbnail/' . $product->imgName));
            }
            $image = $request->file('imageName');
            $filename = time().'.'.$image->extension();

            $destinationPath = public_path('/thumbnail');
            $img = Image::make($image->path());
            $img->resize(100, 100, function ($constraint) {
                $constraint->aspectRatio();
            })->save($destinationPath.'/'.$filename);
            $product->imgName = $filename;
        }

        $product->orderCode = $request->orderCode;
        $product->name = $request->productName;

        $product->statusId = $request->statusId;
        $product->address = $request->address;
        $product->cusName = $request->cusName;
        $product->fbName = $request->fbName;
        $product->fbLink = $request->fbLink;
        $product->updateAt = now();
        $product->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $des = Product::find($id);
        if($des->imgName != 'default.png') {
            File::delete(public_path('/thumbnail/' . $des->imgName));
        }
        $des->delete();

        return back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index(Request $request) {

        $codeKeyword = $request->input('code',null);
        $product = [];
        if($codeKeyword != null) {
            $product = Product::with('Status')->orderBy('id', 'desc')->where('orderCode',$codeKeyword)->paginate(9);
        }

        return view('index', compact('product'));
    }
}

resources/views/Layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/ajax-loading.css') }}" rel="stylesheet">
    @yield('header.cdn')
</head>

<body class="c-app">
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
    <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
        <i class="fas fa-bars"></i>
    </button>
    @include('inc.center.layouts._leftmenu')
</div>
<div class="c-wrapper c-fixed-components">

    <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
        @include('inc.center.layouts._topmenu')
    </header>

    <div class="c-body">
        <main class="c-main">
            @yield('contents')
        </main>
        <footer class="c-footer">
            <div><a href="https://coreui.io">CoreUI</a> &copy; 2020 creativeLabs.</div>
            <div class="ml-auto">Powered by&nbsp;<a href="https://coreui.io/">CoreUI</a></div>
        </footer>
    </div>

</div>

<div class="modal-ajax-loading"></div>

</body>
<script defer src="{{ asset('js/app.js') }}"></script>
<script defer src="{{ asset('js/font.js') }}"></script>
<script src="{{ asset('js/jquery.min.js') }}"></script>
@yield('script')
</html>

resources/views/Layouts/user.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/ajax-loading.css') }}" rel="stylesheet">
    @yield('header.cdn')
</head>

<body class="c-app">
<div class="c-wrapper c-fixed-components">
    <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
        @include('inc.center.layouts._topmenu')
    </header>

    <div class="c-body">
        <main class="c-main">
            @yield('contents')
        </main>
        <footer class="c-footer">
            <div><a href="https://coreui.io">CoreUI</a> &copy; 2020 creativeLabs.</div>
            <div class="ml-auto">Powered by&nbsp;<a href="https://coreui.io/">CoreUI</a></div>
        </footer>
    </div>

</div>

<div class="modal-ajax-loading"></div>

</body>
<script defer src="{{ asset('js/app.js') }}"></script>
<script defer src="{{ asset('js/font.js') }}"></script>
<script src="{{ asset('js/jquery.min.js') }}"></script>
@yield('script')
</html>

resources/views/inc/center/layouts/_leftmenu.blade.php
<div class="c-sidebar-brand d-lg-down-none">
    <img src="{{ asset('image/logo.gif') }}" class="logo-nation" alt="">

    <svg class="c-sidebar-brand-minimized" width="46" height="46" alt="CoreUI Logo">
        <use xlink:href="assets/brand/coreui.svg#signet"></use>
    </svg>
</div>
<ul class="c-sidebar-nav">
    <li class="c-sidebar-nav-title"><strong>Login : </strong> {{ Auth::user()->name }}</li>

    <li class="c-sidebar-nav-item"><a
            class="c-sidebar-nav-link {{ Request::segment(1) == "dashboard" ? "c-active" : "" }}"
            href="{{ route('admin.product.index') }}" >
            <i class="fab fa-product-hunt"></i>
            <span class="ml-4">จัดการ <strong>ORDER</strong> </span>
        </a>
    </li>
    <li class="c-sidebar-nav-item"><a
                class="c-sidebar-nav-link"
                href="{{ route('auth.logout') }}" >
            <i class="fas fa-sign-out-alt"></i>
            <span class="ml-4">ออกจากระบบ </span>
        </a>
    </li>

</ul>

resources/views/inc/center/layouts/_topmenu.blade.php
@if(Request::segment(1) == "admin")
    <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
        <i class="fas fa-bars"></i>
    </button>
@else
    <div class="c-header-toggler c-class-toggler d-lg-none mfe-auto mt-3 ml-3">
        <img src="{{ asset('logo.jpg') }}" alt="" style="width: 100px; height:100px">
        <span class="font-weight-bold">Snow Shop</span>
    </div>
@endif

<a class="c-header-brand d-lg-none" href="#">
    <svg width="118" height="46" alt="CoreUI Logo">
        <use xlink:href="assets/brand/coreui.svg#full"></use>
    </svg>
</a>

@if(Request::segment(1) == "admin")
    <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
        <i class="fas fa-bars"></i>
    </button>
@else
    <div class="c-header-toggler c-class-toggler mfs-3 d-md-down-none mt-3">
        <img src="{{ asset('logo.jpg') }}" alt="" style="width: 100px; height:100px">
        <span class="font-weight-bold">Snow Shop ระบบ ตรวจเช็คสถานะสินค้า</span>
    </div>
@endif

<ul class="c-header-nav d-md-down-none">
    {{-- <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Dashboard</a></li>
    <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Users</a></li>
    <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Settings</a></li> --}}
</ul>
<div class="c-subheader px-3">
    <ol class="breadcrumb border-0 m-0">
        @yield('breadcrumb')
    </ol>
</div>

resources/views/index.blade.php
@extends('Layouts.user')
@section('contents')
    <div class="container-fluid">
        <div class="fade-in">
            <div class="card pr-3 pl-3">

                <div class="row mt-3 ml-2">
                    <blockquote class="blockquote ml-2">
                        <p><em>หมายเหตุ</em></p>
                        <ul>
                            <li>หากขึ้นสถานะ "สินค้ารอตรวจสอบ" ทางเราจะจัดส่งให้ลูกค้าภายใน 2-3 วัน ไม่รวมวันอาทิตย์ค่ะ (กรณีชำระเงินแบบรอบเดียว)</li>
                            <li>หากเป็นลูกค้าที่ชำระเงิน 2 รอบ ให้รอการตอบกลับจากทางแอดมินเพื่อชำระเงินรอบที่ 2 ค่ะ</li>
                            <li>หากสถานะแจ้งว่า "สินค้ารอตรวจสอบ" ลูกค้าสามารถเข้ามาเช็คเลขพัสดุในไทยเพื่อส่งไปบ้านลูกค้าได้ ภายใน 2-3 วัน ไม่รวมวันอาทิตย์ค่ะ</li>
                            <li>ลูกค้าสามารถแจ้งเปลี่ยนที่อยู่จัดส่งได้เมื่อขึ้นสถานะ "กำลังมาไทย" หากต้องการเปลี่ยนที่อยู่จัดส่ง</li>
                        </ul>
                    </blockquote>

                </div>
                <div class="card-header">
                    <form action="" method="GET">
                        <div class="row">
                            <div class="col-md-6">
                                <b>กรอกเลขคำสั่งซื้อของคุณ</b>
                                <input type="text" class="form-control mt-1" name="code" placeholder="101102" value="{{ empty($_GET['code']) ? null : $_GET['code'] }}">
                            </div>
                            <div class="col-md-6">
                                <input type="submit" class="btn btn-info mt-4" value="ค้นหา">
                            </div>
                        </div>
                    </form>
                </div>
                <div style="overflow-x:auto;">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">เลขที่สั่งซื้อ</th>
                            <th scope="col">รูปภาพ</th>
                            <th scope="col">ชื่อสินค้า</th>
                            <th scope="col">Facebook ลูกค้า</th>
                            <th scope="col">สถานะสินค้า</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($product))
                            @foreach($product as $products)
                                <tr>
                                    <td>{{ $products->orderCode }}</td>
                                    <td>
                                        <img src="{{ asset('thumbnail/'.$products->imgName) }}" alt="">
                                    </td>
                                    <td>{{ $products->name }}</td>
                                    <td><a href="{{ $products->fbLink }}">{{ $products->fbName }}</a></td>
                                    <td>
                                        <span class="{{ $products->status->class }}">{{ $products->status->statusName }}</span>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="5" style="text-align: center">กรอกคำสั่งซื้อของคุณ</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end">
                        @if(!empty($product))
                            {{ $product->links() }}
                        @endif
                    </ul>
                </nav>
            </div>
        </div>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('Layouts.main')
@section('contents')
    <div class="container-fluid">
        <div class="fade-in">
            <div class="card pr-3 pl-3">
                <div class="card-header">
                    <div class="row">

                        <div class="col-md-7">
                            <form action="" method="GET">
                                <div class="row">
                                    <div class="col-md-6">
                                        <b>กรอกเลขคำสั่งซื้อของคุณ</b>
                                        <input type="text" class="form-control mt-1" name="code" placeholder="101102" value="{{ empty($_GET['code']) ? null : $_GET['code'] }}">
                                    </div>
                                    <div class="col-md-6">
                                        <input type="submit" class="btn btn-info mt-4" value="ค้นหา">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-4 text-right mt-3">
                            <a href="{{ route('admin.product.create') }}" class="btn btn-info">เพิ่ม Order</a>
                        </div>
                    </div>
                </div>
                <div style="overflow-x:auto;">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">เลขที่สั่งซื้อ</th>
                            <th scope="col">รูปภาพ</th>
                            <th scope="col">ชื่อสินค้า</th>
                            <th scope="col">Facebook ลูกค้า</th>
                            <th scope="col">สถานะสินค้า</th>
                            <th scope="col">วันที่เพิ่มข้อมูล</th>
                            <th scope="col">จัดการ</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($product as $products)
                            <tr>
                                <td>{{ $products->orderCode }}</td>
                                <td>
                                    <img src="{{ asset('thumbnail/'.$products->imgName) }}" alt="">
                                </td>
                                <td>{{ $products->name }}</td>
                                <td><a href="{{ $products->fbLink }}">{{ $products->fbName }}</a></td>
                                <td><span class="{{ $products->status->class }}">{{ $products->status->statusName }}</span>
                                <td><span class="badge bg-secondary">{{ formatDateThat($products->createAt) }}</span></td>
                                <td>
                                    <a href="{{route('admin.product.edit',$products->id)}}" class="btn btn-warning">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <button class="btn btn-danger btn-delete" data-id="{{ $products->id }}">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end">
                        {{ $product->links() }}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    @include('product.modal')
@endsection
@section('script')
    <script>
        $('.btn-delete').click(function() {
            let id = $(this).attr('data-id');
            document.getElementById("formdelete").action = '{{ url("admin/product") }}/' + id;
            $('#deleteModal ').modal('show')
        });
    </script>
@endsection

resources/views/product/manage.blade.php
@extends('Layouts.main')
@section('contents')
    <div class="container-fluid">
        <div class="fade-in">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8">
                            <b>{{ empty($text) ? 'เพิ่ม' : $text }}สินค้า</b>
                        </div>
                        <div class="col-md-4 text-right">
                            <a href="{{ route('admin.product.index') }}" class="btn btn-info">ย้อนกลับ</a>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <form class="mt-3" method="POST"
                          action="{{ empty($text) ? route('admin.product.store') : route('admin.product.update',['product' => $product->id]) }}"
                          enctype="multipart/form-data">
                        @csrf
                        @if(!empty($text))
                            @method('PUT')
                        @endif

                        @if(!empty($product->imgName))
                            <div class="row">
                                <img src="{{ asset('thumbnail/'.$product->imgName) }}" alt="" class="ml-3">
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="exampleFormControlFile1">รูปภาพสินค้า</label>
                            <input type="file" name="imageName" class="form-control-file" id="exampleFormControlFile1">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlInput1">เลขคำสั่งซื้อ</label>
                            <input type="text" class="form-control" name="orderCode"
                                   value="{{ !empty($product->orderCode) ? $product->orderCode : '' }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlInput1">ชื่อสินค้า</label>
                            <input type="text" class="form-control" name="productName"
                                   value="{{ !empty($product->name) ? $product->name : '' }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">ที่อยู่จัดส่ง</label>
                            <textarea class="form-control" rows="3"
                                      name="address">{{ !empty($product->address) ? $product->address : '' }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">สถานะสินค้า</label>
                            <select class="form-control" id="exampleFormControlSelect1" name="statusId">
                                @foreach($status as $statuses)
                                    <option value="{{ $statuses->id }}" {{ !empty($product->statusId) ? ($statuses->id == $product->statusId) ? 'selected' : '' : '' }}>{{ $statuses->statusName }}</option>
                                @endforeach
                            </select>
                        </div>
                        <hr>
                        <strong>ข้อมูลผู้สั่งซื้อ</strong>
                        <div class="form-group mt-3">
                            <label for="exampleFormControlInput1">ชื่อลูกค้า</label>
                            <input type="text" class="form-control" placeholder="คุณ..." name="cusName"
                                   value="{{ !empty($product->cusName) ? $product->cusName : '' }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlInput1">ชื่อ Facebook</label>
                            <input type="text" class="form-control" placeholder="FaceBook Name" name="fbName"
                                   value="{{ !empty($product->fbName) ? $product->fbName : '' }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Facebook Link</label>
                            <input type="text" class="form-control" placeholder="www.facebook.com" name="fbLink"
                                   value="{{ !empty($product->fbLink) ? $product->fbLink : '' }}">
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary mb-2" style="float: right;"
                                   value="บันทึกข้อมูล">
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/product/modal.blade.php
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="formdelete">
            @csrf
            @method('DELETE')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">คำเตือน</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    คุณต้องการลบใช่หรือไม่ !?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">ยกเลิก</button>
                    <button type="submit" class="btn btn-primary" id="saveData">ยืนยัน</button>
                </div>
            </div>
        </form>
    </div>
</div>